---
title: "running_alert_aws_lambda"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

AWS solves one of the biggest problems within analytics: The Last Mile. This is basically "I developed something that works locally or in a cloud-based Sandbox environment" to "This is going to be accessible to others in the real-world". The key about analytics is that value is only realized in the second stage, yet very little time is spent on it. Thus, the goal of this to highlight an AWS service that I've found to have many helpful applications - Lambda - through an real-life use-case. 

### Why I don't plan a run on weather forecasts



### Part 1: 


### Configuring Environment

Functions -> Configuration -> Environment Variables
"use image add_environment_variables"

Change how long you want the lambda to run for. 3 seconds is very fast. If you are accessing an API you'll likely need longer :)



### Adding Layers
here is how you do it

### Adding Permissions
Configuration -> Execution Role -> Permissions -> Attach Policies 
* AmazonS3FullAccess - allows lambda to access S3
* AmazonSES FullAccess - allows lambda to send emails 


### Creating an S3 Bucket to land data

### Setting up Triggers



`arn:aws:sts::371410071971:assumed-role/time-to-run/SendRunningEmail' is not authorized to perform `ses:SendEmail'




