---
title: "Causal Inference Part 1: Propensity Scores"
author: "Mark LeBoeuf"
date: '2021-03-15T21:13:14-05:00'
summary: A Summary
tags:
- Fantasy Football
- Python
- R
- Beta Distribution
categories:
- Fantasy Football
- Python
- R
- Beta Distribution
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


The main goal is to create a control group when you cannot randomly assign individuals. A simple example might be. Propensity scores are an appropriate way to address selection bias, which basically 

- You have latent variables that are related to the chance of being exposed to the ad and the outcome. 

- Model predicts the probability of exposure between those who were exposed relative to those who were not exposed. 
- Probability of being exposed given a set of predictors. 

Propensity Scores just take all of these variables and shrink it down to a single score. Goal is to make selection strongly ignorable. 

Want to find things that predict (1) exposure and (2) the outcome. 

Need a theory of selection that you can rely on what features or characteristics of the individual that are going to affect both exposure and the outcome. 
Past behaviors that happened prior to the exposure. 









How much does Y change when you change X? A simplest approach is to . On average, there shouldn't be a difference between your groups. But experiments are hard to do. For example, if you create a membership program, does being a member cause individuals to spend more money on your website? The problem here is that you cannot randomly assign some people to be a subscribers and others to a non-subscription. Furthermore, the act of . So if you simply find that You might br correct. Further, depending on the maturity of the platform, implementing a/b tests at scale requires a mature set-up; you have to be able to funnel traffic between conditions and 

The goal is to "simulate" this through creative analysis. Let's take a seperate example. Imagine you are interested in the effect of a 20% discount on a consumers tendency to purchase. The marketing team decides to 

Counterfactual thinking. What would have happened had we not changed X? Let's put this into an example. 





Causal -> Cause & Effect. 
Causal Inference -> Draw conclusions between cause & effect 
A -> B
B -> A 
Z -> A
Z -> B

Why A/B Test?
- This is the "simplest" way to make a causal inference. However, A/B testing is not always simple or feasible. It can be impossible 
Causal Inference answers the question "What would happen"? How much more beer would we sell if we buy more google ads?

Goal: Infer the effect of one thing on another
- Effect of treatment on disease
- Effect of website change on conversion
- Effect of climate change policy on emissions 

- Observational studies are just more convienient. 
- Adjust/control for confounders 



How do you measure causal effects in observational studies? 

### Simpson's Paradox






BING BONG!!!
Need to answer Causal graphs. This is different from traditional machine learnining, where the goal is map F(x) -> y. Goal is to explain the structure. 

Inputs, Interventions (T), and Outputs. What is the causal relationship between these three variables? 

X is what you know about the person. X -> T (treatment plan -> binary (treatment 1, treatment 2))

Challenge is you only observe one outcome. And you must impute the other outcome. And this is the crux of the counterfactual. 

Conditional Average Treatment Effect (For someone with a specific age, there is a big difference between the two treatments). What you want to predict. 

Average treatment effect (does not condition on any variable) (On average, this intervention is a good intervention)



